"""1

Revision ID: 4279ed04a858
Revises: 
Create Date: 2022-02-09 11:16:33.025915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4279ed04a858'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('name_user', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=102), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('name_user')
    )
    op.create_table('posts',
    sa.Column('id_post', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(length=1500), nullable=False),
    sa.Column('created_date_time', sa.String(length=16), nullable=False),
    sa.Column('updated_date_time', sa.String(length=16), nullable=False),
    sa.Column('users_id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['users_id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_post')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
